# Generated by Django 3.2.15 on 2024-01-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('software', '0001_initial'),
        ('commentswitharticles', '0001_initial'),
        ('frontenduser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='correlation_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentswitharticles.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontenduser.frontenduser'),
        ),
        migrations.AddField(
            model_name='article',
            name='correlation_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontenduser.frontenduser'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('correlation_article', 'correlation_software')},
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'correlation_software')},
        ),
    ]
