# Generated by Django 3.2.15 on 2024-01-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_software_user'),
        ('commentsWithArticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='correlation_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
        migrations.AddField(
            model_name='comment',
            name='correlation_model',
            field=models.IntegerField(choices=[(1, '文章'), (2, '软件')], default=1),
        ),
    ]
