# Generated by Django 3.2.15 on 2024-01-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_software_user'),
        ('commentsWithArticles', '0002_auto_20240123_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='correlation_model',
        ),
        migrations.AddField(
            model_name='comment',
            name='correlation_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentsWithArticles.article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='correlation_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
    ]
