# Generated by Django 3.2.15 on 2024-01-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsWithArticles', '0003_auto_20240123_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='correlation_model',
            field=models.IntegerField(choices=[(1, '文章'), (2, '软件')], default=1),
        ),
    ]
