# Generated by Django 3.2.23 on 2024-02-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentswitharticles', '0004_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='article/default.png', upload_to='article'),
        ),
    ]
