# Generated by Django 3.2.23 on 2024-03-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20240317_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='question',
        ),
    ]
