# Generated by Django 3.2.23 on 2024-04-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answer_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_adopt',
            field=models.IntegerField(choices=[(0, '未采纳'), (1, '已采纳')], default=0),
        ),
    ]
