# Generated by Django 3.2.23 on 2024-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontenduser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontenduser',
            name='head_icon',
            field=models.ImageField(default='user/default_head_icon.png', upload_to='user'),
        ),
    ]
