# Generated by Django 3.2.15 on 2024-01-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20240125_2324'),
        ('frontenduser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontenduser',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='favorites.favorites'),
        ),
    ]
