# Generated by Django 3.2.15 on 2024-01-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsWithArticles', '0005_auto_20240125_2324'),
        ('favorites', '0002_auto_20240125_2324'),
        ('software', '0004_auto_20240125_2324'),
        ('frontenduser', '0002_frontenduser_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontenduser',
            name='favorite',
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='favorites_article',
            field=models.ManyToManyField(related_name='favorites_article', through='favorites.Favorites', to='commentsWithArticles.Article'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='favorites_software',
            field=models.ManyToManyField(related_name='favorites_software', through='favorites.Favorites', to='software.SoftWare'),
        ),
    ]
