# Generated by Django 3.2.23 on 2024-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontenduser', '0002_frontenduser_head_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontenduser',
            name='head_icon',
            field=models.ImageField(default='user/default_head_icon.ico', upload_to='user'),
        ),
    ]
