# Generated by Django 3.2.15 on 2024-01-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontenduser', '0003_auto_20240125_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontenduser',
            old_name='favorites_article',
            new_name='favorite_articles',
        ),
        migrations.RenameField(
            model_name='frontenduser',
            old_name='favorites_software',
            new_name='favorite_softwares',
        ),
    ]
