# Generated by Django 3.2.23 on 2024-02-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontenduser', '0004_frontenduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontenduser',
            name='role',
            field=models.CharField(choices=[('普通用户', '普通用户'), ('管理员', '管理员'), ('写手', '写手'), ('开发者', '开发者')], default='普通用户', max_length=50),
        ),
    ]
