# Generated by Django 3.2.15 on 2024-01-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontenduser', '0005_auto_20240125_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontenduser',
            old_name='favorite_articles',
            new_name='favorite',
        ),
    ]
