# Generated by Django 3.2.23 on 2024-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontenduser', '0006_alter_frontenduser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontenduser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
