# Generated by Django 3.2.15 on 2024-01-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontenduser', '0006_rename_favorite_articles_frontenduser_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontenduser',
            name='favorite',
        ),
    ]
