# Generated by Django 3.2.15 on 2023-11-27 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commentsandposts', '0001_initial'),
        ('frontenduser', '0001_initial'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.software')),
                ('articles',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentsandposts.article')),
                (
                'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontenduser.frontenduser')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
    ]
