# Generated by Django 3.2.15 on 2024-01-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontenduser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('article', 'article'), ('app', 'app')], default='article', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontenduser.frontenduser')),
            ],
            options={
                'verbose_name': '收藏管理',
                'verbose_name_plural': '收藏管理',
            },
        ),
    ]
