# Generated by Django 3.2.15 on 2023-12-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='apps',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='articles',
        ),
        migrations.AddField(
            model_name='favorites',
            name='type',
            field=models.CharField(choices=[('article', 'article'), ('comment', 'comment')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
