# Generated by Django 3.2.15 on 2024-01-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_auto_20240125_2324'),
        ('commentsWithArticles', '0005_auto_20240125_2324'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='date',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='favorites',
            name='correlation_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentsWithArticles.article'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='correlation_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('correlation_article', 'correlation_software')},
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='type',
        ),
    ]
