# Generated by Django 3.2.15 on 2023-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20231205_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='type',
            field=models.CharField(choices=[('article', 'article'), ('app', 'app')], max_length=100),
        ),
    ]
