# Generated by Django 3.2.23 on 2024-02-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
