# Generated by Django 3.2.15 on 2024-01-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('icon', models.ImageField(null=True, upload_to='category/icons/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '软件分类',
                'verbose_name_plural': '软件分类',
            },
        ),
    ]
