# Generated by Django 3.2.23 on 2024-02-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.IntegerField(choices=[(0, '停用'), (1, '正常')], db_index=True, default=1),
        ),
    ]
