# Generated by Django 3.2.23 on 2024-02-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.IntegerField(choices=[(1, '停用'), (2, '正常')], db_index=True, default=2),
        ),
    ]
