# Generated by Django 3.2.15 on 2024-01-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentsandposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time'], 'verbose_name': '文章管理', 'verbose_name_plural': '文章管理'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name': '评论审核中心', 'verbose_name_plural': '评论审核中心'},
        ),
    ]
