# Generated by Django 3.2.15 on 2024-01-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('software', '0002_alter_software_id'),
        ('announcements', '0003_alter_announcements_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='software.software'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='type',
            field=models.IntegerField(choices=[(0, '全站'), (1, '指定APP')], default=0),
        ),
    ]
