# Generated by Django 3.2.15 on 2024-01-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcements_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'ordering': ['-created_time'], 'verbose_name': '公告管理', 'verbose_name_plural': '公告管理'},
        ),
        migrations.RenameField(
            model_name='announcements',
            old_name='date',
            new_name='created_time',
        ),
    ]
