# Generated by Django 3.2.15 on 2024-01-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20240110_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'ordering': ['-date'], 'verbose_name': '公告管理', 'verbose_name_plural': '公告管理'},
        ),
    ]
