# Generated by Django 3.2.15 on 2024-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcements_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements'),
        ),
    ]
