# Generated by Django 3.2.15 on 2024-01-16 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftWare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link_adrive', models.URLField(blank=True, null=True)),
                ('link_baidu', models.URLField(blank=True, null=True)),
                ('link_direct', models.URLField(blank=True, null=True)),
                ('link_123', models.URLField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='software')),
                ('status', models.IntegerField(choices=[(1, '未审核'), (2, '已审核'), (3, '已下架')], default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '软件管理',
                'verbose_name_plural': '软件管理',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareScreenShots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='software/screenshots')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.software')),
            ],
        ),
    ]
