# Generated by Django 3.2.15 on 2024-01-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
