# Generated by Django 3.2.15 on 2024-01-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='status',
            new_name='state',
        ),
    ]
