# Generated by Django 3.2.23 on 2024-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='download_volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='software',
            name='thumbs_volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='software',
            name='view_volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
