# Generated by Django 3.2.15 on 2023-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
