# Generated by Django 3.2.15 on 2024-01-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_software_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwarescreenshots',
            options={'verbose_name': '软件截图管理', 'verbose_name_plural': '软件截图管理'},
        ),
        migrations.AddField(
            model_name='software',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='official_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='platform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='run_os_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
