# Generated by Django 3.2.15 on 2024-01-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_software_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-date'], 'verbose_name': 'Software', 'verbose_name_plural': 'Software'},
        ),
    ]
