# Generated by Django 3.2.15 on 2024-01-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_alter_software_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-date'], 'verbose_name': '软件管理', 'verbose_name_plural': '软件管理'},
        ),
    ]
