# Generated by Django 3.2.15 on 2024-01-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_software_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-updated_time'], 'verbose_name': '软件管理', 'verbose_name_plural': '软件管理'},
        ),
        migrations.RenameField(
            model_name='software',
            old_name='create_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='update_date',
            new_name='updated_time',
        ),
    ]
